### ISSUE TITLE
Error by OPCUA-Client command after installing all packages

### ISSUE THREAD

**Issue by JacksonJoy** [FreeOpcUa/opcua-client-gui#38]
Hi,
I am trying to make raspberry pi 3 as client to visualize my data. 
At the final step after installing opcua and opcua-client **i cannot run the opc-ua client.** 

It is showing invalid syntax. I am using Python 3.5.3. Is the syntax different. I am stuck. Could someone please help

pi@raspberrypi:~ $ opcua-client
pyqtgraph or numpy are not installed, use of graph feature disabled
Traceback (most recent call last):
  File "/usr/local/bin/opcua-client", line 7, in <module>
    from uaclient.mainwindow import main
  File "/usr/local/lib/python3.5/dist-packages/uaclient/mainwindow.py", line 23, in <module>
    from uawidgets.attrs_widget import AttrsWidget
  File "/home/pi/.local/lib/python3.5/site-packages/uawidgets/attrs_widget.py", line 11, in <module>
    from uawidgets.get_node_dialog import GetNodeButton
  File "/home/pi/.local/lib/python3.5/site-packages/uawidgets/get_node_dialog.py", line 7, in <module>
    from uawidgets.tree_widget import TreeWidget
  File "/home/pi/.local/lib/python3.5/site-packages/uawidgets/tree_widget.py", line 62
    raise ValueError(f"Node {node} not found in tree")
                                                    ^
SyntaxError: invalid syntax

**Comment by zerox1212** [comment]
Do you have all dependencies such s PyQT 5?

**Comment by oroulet** [comment]
This is a python 3.6 that went in....  F-string is 3.6

**Comment by JacksonJoy** [comment]
> Do you have all dependencies such s PyQT 5?

Thank you zerox1212. Yes I have installed PyQT5. It went succesfully.

**Comment by JacksonJoy** [comment]
> This is a python 3.6 that went in.... F-string is 3.6

Thank you oroulet. But my version is Python 3.5.3. Should I update my python in raspberry pi to 3.6?

**Comment by zerox1212** [comment]
Yes, you need python 3.6 or higher.

**Comment by cbergmiller** [comment]
From the stack trace it looks like the f-string is in _uawidgets_
In the master branch there is no f-string in tree_widgets.py:
https://github.com/FreeOpcUa/opcua-widgets/blob/master/uawidgets/tree_widget.py
How can that be?

**Comment by oroulet** [comment]
He uses the released version and I probably fixed master

**Comment by JacksonJoy** [comment]
Hi. I edited the tree_widget.py, so that it can run on python 3.5. Then it functioned. Thank you everyone for the help

**Comment by Knight9206** [comment]
@JacksonJoy 
hi, i also have some problem about in raspberry pi 3+.
how did you deit your tree_widget.py. I try to upgrade python 3.6 and i can not resolve that problem.
can you give me some comment?

**Comment by vivaladav** [comment]
Replacing all the occurrences of **(f"** with (" in _uawidgets/tree_widget.py_ allows to run it fine with Python 3.5.

For example  
_raise ValueError(f"Node {node} not found in tree")_
should become
_raise ValueError("Node {node} not found in tree")_

@Knight9206

**Comment by shraddha291996** [comment]
Hello,
While installing OPCUA connector kafka I am getting this error I have attached. I tried searching on google but could not find anything to solve the error. Could anyone please help :) Thanks in advance.
![Capture](https://user-images.githubusercontent.com/59836701/89432573-958b4580-d741-11ea-85d8-84029d64fb4e.PNG)

**Comment by rupesharora** [comment]
I encountered with same issue. Resolved by running following commands.
`sudo apt install pyqt5-dev-tools pyqt5-dev`

If still doesn't work try below too:
`sudo apt-get install python3-pyqt5`
