### ISSUE TITLE
Client crash when setting node's DisplayName on server

### ISSUE THREAD

**Issue by amgfreak** [FreeOpcUa/opcua-client-gui#42]
Hi together,

after instantiating a node on my server and setting a display name, sometimes the client can't connect to the server anymore (before it was working properly), sometimes it can connect to the server, but if I try to open the folder with the node in it, it crashes. In my terminal window I get these messages:
`uaclient.uaclient - INFO - Connecting to opc.tcp://localhost:4842 with parameters None_, None, , ')
uaclient.mainwindow - WARNING - showing error: %s')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uawidgets/tree_widget.py", line 244, in fetchMore
    self._fetchMore(parent)
  File "/usr/local/lib/python3.7/site-packages/uawidgets/tree_widget.py", line 249, in _fetchMore
    descs = node.get_children_descriptions()
  File "/usr/local/lib/python3.7/site-packages/opcua/common/node.py", line 338, in get_children_descriptions
    return self.get_references(refs, ua.BrowseDirection.Forward, nodeclassmask, includesubtypes)
  File "/usr/local/lib/python3.7/site-packages/opcua/common/node.py", line 367, in get_references
    results = self.server.browse(params)
  File "/usr/local/lib/python3.7/site-packages/opcua/client/ua_client.py", line 306, in browse
    data = self._uasocket.send_request(request)
  File "/usr/local/lib/python3.7/site-packages/opcua/client/ua_client.py", line 78, in send_request
    data = future.result(self.timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 437, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
Abort trap: 6`

Does anyone know how to handle this?

**Comment by amgfreak** [comment]
The node is instantiated with: 
'from opcua import instantiate as iN
cNode = iN(destinationNode, nodeTypedef, bname='string', idx=2, dname='string')'
where destinantionNode is a folder and nodeTypedef the typedef of the node (in namespace 2, created with opcua-modeler)
