### ISSUE TITLE
Crash when clicking on Variable (Windows)

### ISSUE THREAD

**Issue by cmorty** [FreeOpcUa/opcua-client-gui#7]
When clicking on a Variable-Node I get:

```
Traceback (most recent call last):
  File "c:\users\mstruebe\appdata\local\programs\python\python35-32\lib\site-packages\freeopcuaclient\mainwindow.py", line 198, in show_attrs
    self._show_attrs(node)
  File "c:\users\mstruebe\appdata\local\programs\python\python35-32\lib\site-packages\freeopcuaclient\mainwindow.py", line 211, in _show_attrs
    v = v.to_string()
  File "c:\users\mstruebe\appdata\local\programs\python\python35-32\lib\site-packages\opcua\ua\uatypes.py", line 739, in to_string
    return self.Text.decode()
AttributeError: 'NoneType' object has no attribute 'decode'
```

This happens for example when clicking on the ServerStatus, but other variables, too.

**Comment by oroulet** [comment]
thanks. need to fix that...
