### ISSUE TITLE
Unable to install opcua-client on armv7 raspberry pi

### ISSUE THREAD

**Issue by munishreddy1** [FreeOpcUa/opcua-client-gui#91]
Hi,
I created an API to read values from my PLC by enabling opc server and created a client on my PC I build a docker image with all dependencies in amd64 architecture. But when I am trying to build an image with armv7 architecture it is throwing an error while installing the PyQt5 package. I found it is the issue with the python version in some forums and tried with different python versions but I got the same error

I tried to install PyQT5 globally on my raspberry pi and got the same error. Can anyone help me with this? 
Error:

error: subprocess-exited-with-error

× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [30 lines of output]
Querying qmake about your Qt installation...
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in
main()
File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
whl_basename = backend.build_wheel(metadata_directory, config_settings)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
project = AbstractProject.bootstrap('wheel',
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
project.setup(pyproject, tool, tool_description)
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 585, in setup
self.apply_user_defaults(tool)
File "/tmp/pip-install-n7wvxyan/pyqt5_eecbbf17d381465997ddd8547dd4cb77/project.py", line 68, in apply_user_defaults
super().apply_user_defaults(tool)
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
super().apply_user_defaults(tool)
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
self.builder.apply_user_defaults(tool)
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 78, in apply_user_defaults
self._get_qt_configuration()
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 493, in _get_qt_configuration
for line in project.read_command_pipe([self.qmake, '-query']):
File "/tmp/pip-build-env-b5pupna4/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 553, in read_command_pipe
raise UserException(
sipbuild.exceptions.UserException
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.**

note: This is an issue with the package mentioned above, not pip.

**Comment by schroeder-** [comment]
If installing PyQt5 is a problem, you should contact the developer of PyQt5.
