### ISSUE TITLE
Can't run the application

### ISSUE THREAD

**Issue by juan11iguel** [FreeOpcUa/opcua-client-gui#93]
Hi, I have been using this client for a long time, but after trying to install it in a new system (running fedora), after installing the pip package with `pip install opcua-client` the opcua-client command is not added to the path / configured correctly. I have been trying to find where the package is installed and running the python scripts manually (`python mainwindow.py`) with no luck either.  

Has anyone faced a similar problem and can point me in the right direction?

Thanks!

I also tried with the snap but it does not work:
```bash
Traceback (most recent call last):
  File "/snap/opcua-client/30/bin/opcua-client", line 33, in <module>
    sys.exit(load_entry_point('opcua-client==0.8.4', 'console_scripts', 'opcua-client')())
  File "/snap/opcua-client/30/bin/opcua-client", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/snap/opcua-client/30/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/snap/opcua-client/30/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/snap/opcua-client/30/lib/python3.6/site-packages/uaclient/mainwindow.py", line 15, in <module>
    from asyncua import ua
  File "/snap/opcua-client/30/lib/python3.6/site-packages/asyncua/__init__.py", line 12, in <module>
    from .common import Node, uamethod
  File "/snap/opcua-client/30/lib/python3.6/site-packages/asyncua/common/__init__.py", line 1, in <module>
    from .node import Node
  File "/snap/opcua-client/30/lib/python3.6/site-packages/asyncua/common/node.py", line 9, in <module>
    from asyncua import ua
  File "/snap/opcua-client/30/lib/python3.6/site-packages/asyncua/ua/__init__.py", line 6, in <module>
    from .uaprotocol_auto import *
  File "/snap/opcua-client/30/lib/python3.6/site-packages/asyncua/ua/uaprotocol_auto.py", line 9, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by juan11iguel** [comment]
Nevermind, I was trying in the site-packages directory, should have looked in this directory instead: `$HOME/.local/bin/opcua-client` and was able to run it simply with `python $HOME/.local/bin/opcua-client`.

For anyone facing the same problem, once you identify where the executable is, you can create an alias either in bashrc or zshrc to be able to run the app with `opcua-client`.

```
alias opcua-client="python $HOME/.local/bin/opcua-client" 
```

As a suggestion, I think packaging the application as a flatpak would help the application reach a wider audience.

Congrats for the project!

**Comment by gdargaud** [comment]
Same problem here but indicated solution doesn't work:

```
$ opcua-client 
[...]
ModuleNotFoundError: No module named 'dataclasses'
$ which opcua-client 
/snap/bin/opcua-client
$ ll /snap/bin/opcua-client
lrwxrwxrwx 1 root root 13 May 20  2025 /snap/bin/opcua-client@ -> /usr/bin/snap

```
It's an executable, not a python script, so I can't preface it with 'python' to run it.
